UPDATE `penalitzacio` SET `punts` = '-1' WHERE `id_concursant` = 2 LIMIT 1;


INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 
INSERT INTO `penalitzacio` ( `id_concursant` , `punts` ) VALUES ( '' , '0' ) ; 